
---
name: "Release Odyssey"

on:
  push:
    branches:
    - "master"
  release:

jobs:
  release-please:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "googleapis/release-please-action@v4"
      with:
        release-type: "simple"
  build-images:
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image Odyssey
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.release-please.outputs.tag_name }}
